name: dantex
description: Dante - Book Tracker Cross Platform implementation.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.1.4
  go_router: ^14.4.1
  flutter_riverpod: ^2.6.1
  firebase_auth: ^5.3.2
  riverpod_annotation: ^2.6.1
  easy_localization: ^3.0.7
  google_fonts: ^6.2.1
  firebase_core: ^3.7.0
  google_sign_in: ^6.2.2
  logger: ^2.4.0
  firebase_analytics: ^11.3.4
  email_validator: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  strict: ^2.1.0
  patrol_finders: ^2.2.0+1
  firebase_auth_mocks: ^0.14.1
  mock_exceptions: ^0.8.2
  google_sign_in_mocks: ^0.3.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/logo/ic-launcher.jpg'
  web:
    generate: true
    image_path: 'assets/logo/ic-launcher.jpg'
    theme_color: '#2196f3'

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/logo/
    - assets/lottie/
    - assets/images/
    - assets/translations/
