name: dantex
description: Dante - Book Tracker Cross Platform implementation.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  country_icons: ^3.0.0
  device_marketing_names: ^1.0.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  easy_localization: ^3.0.7
  email_validator: ^3.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  file_picker: ^8.1.4
  firebase_analytics: ^11.3.4
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.7
  fl_chart: ^0.70.2
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_carousel_widget: ^3.1.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.15
  freezed_annotation: ^2.4.4
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  language_picker: ^0.4.5
  logger: ^2.4.0
  lottie: ^3.1.3
  package_info_plus: ^8.1.1
  percent_indicator: ^4.2.4
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  sleek_circular_slider: ^2.0.1
  timeline_tile: ^2.0.0
  ulid: ^2.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  firebase_auth_mocks: ^0.14.1
  firebase_database_mocks: ^0.7.1
  firebase_storage_mocks: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  google_sign_in_mocks: ^0.3.0
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  mock_exceptions: ^0.8.2
  mockito: ^5.4.4
  patrol_finders: ^2.2.0+1
  riverpod_generator: ^2.6.2
  strict: ^2.1.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/ic-launcher.jpg"
  web:
    generate: true
    image_path: "assets/logo/ic-launcher.jpg"
    theme_color: "#2196f3"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/logo/
    - assets/lottie/
    - assets/images/
    - assets/translations/
